### ISSUE TITLE
Failed to enable blenderfds28x

### ISSUE THREAD

**Issue by fuyans** [firetools/blenderfds28x#1]
Blender version: 2.8
BlenderFDS version: n/a ([last commit](https://github.com/firetools/blenderfds/commit/b2fa47a4fceb3ff3efa9bc1a874252142a2f5ad3))

Successfully installed the plugin but failed to enable it (ticking the box) and got the following error message:

```shell
Modules Installed (blenderfds28x-master) from 'C:\\Users\\ian\\Downloads\\blenderfds28x.zip' into 'C:\\Users\\ian\\AppData\\Roaming\\Blender Foundation\\Blender\\2.80\\scripts\\addons'
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender\2.80\scripts\modules\addon_utils.py", line 384, in enable
    mod.register()
  File "C:\Users\ian\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\blenderfds28x-master\__init__.py", line 57, in register
    preferences.register()
  File "C:\Users\ian\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\blenderfds28x-master\bl\preferences.py", line 88, in register
    bpy.utils.register_class(BFPreferences)
ValueError: register_class(...): already registered as a subclass
```

**Comment by emanuelegissi** [comment]
Please rename the "blenderfds28x-master" directory to "blenderfds28x" and
let me know.
Do not forget that this is not yet released, it's a development version.
Emanuele

**Comment by fuyans** [comment]
Gotta. Will give it a shot and keep you posted.

**Comment by fuyans** [comment]
Yes, I am aware this is a dev version. I'm willing to lend a hand testing it.

**Comment by emanuelegissi** [comment]
Thank you!

**Comment by fuyans** [comment]
Worked after renaming both the downloaded .zip and the folder within the .zip file. Cheers.

**Comment by emanuelegissi** [comment]
Ok, I updated the instructions on the wiki. Thanks
