### ISSUE TITLE
If an imported FDS file has a backslash into "FYI" it returns an error

### ISSUE THREAD

**Issue by rupole1185** [firetools/blenderfds28x#13]
I tried to import an FDS file (https://github.com/firemodels/fds/blob/master/Validation/WTC/FDS_Input_Files/WTC_02.fds). It returned me an error because of the backslash presence in the FYI field.

      FYI                = 'Isolatek BLAZE-SHIELD DC/F'

**Comment by emanuelegissi** [comment]
Right. There is a check in strings preventing the "/" char. This should be removed, but some checks on importing should be done before.

**Comment by rupole1185** [comment]
This issue is solved by pull request #24 .

**Comment by emanuelegissi** [comment]
Done
