### ISSUE TITLE
Verification: Import all FDS validation and verification cases as verification for BlenderFDS

### ISSUE THREAD

**Issue by emanuelegissi** [firetools/blenderfds28x#23]
The verification.py script should clone the:
`https://github.com/firemodels/fds/tree/master/Validation`
and the:
`https://github.com/firemodels/fds/tree/master/Verification`
directories. Then import each case into BlenderFDS as an import test.

**Comment by rupole1185** [comment]
@emanuelegissi this task is partially done by the "https://github.com/firetools/blenderfds28x/blob/master/verification/import-verification-fds.sh" script. I need to double check it and maybe extend a bit its functionalities.

Is this a good starting point?

**Comment by emanuelegissi** [comment]
Yes, indeed.
I was thinking about the verification script cloning the verification and
validation script locally (if net available) and then running the tests,
without having to maintain a separate copy of it.
I am preparing a dedicated server to run the tests on a daily basis.
Emanuele

**Comment by rupole1185** [comment]
Ok. I can check the script to achieve the goal. Sorry for the late reply, but I am not receiving notification for this chat ... I turn them on now!

**Comment by emanuelegissi** [comment]
done
