### ISSUE TITLE
Export option: export selected only

### ISSUE THREAD

**Issue by TristanHehnen** [firetools/blenderfds28x#27]
Hi!

It would be nice if there could be an option in the `Export/NIST FDS` dialoge to limit exporting to selected objects only. This should then contain also the assigend materials. right now it seems that even unused `SURF` are exportet. Basically asking for the functionality that is available for the other export modes, e.g. for `Export/Stl`.

I noticed that, because I wanted to export a geometry that I had built in the example file but I removed the burner. Still the `Burner bc` `SURF` was exported and stopped FDS due to the fact that no `REAC` line was specified.

Thanks,
Tristan

EDIT: Typo

**Comment by emanuelegissi** [comment]
Hi Tristan,
This is definitely and easily feasible.
I am adding it in the next days.
Thanks,
Emanuele

**Comment by TristanHehnen** [comment]
Great, thank you very much!

**Comment by emanuelegissi** [comment]
It is fixed. Note that I moved the repo back to blenderfds yesterday.
It works with Blender 2.90

**Comment by TristanHehnen** [comment]
Thank you very much!
