### ISSUE TITLE
permissions error with for make manifold

### ISSUE THREAD

**Issue by rmcdermo** [firetools/blenderfds28x#4]
Dear Emanuele,

I tried to follow the instructions for installing the cloned blenderfds28x per your README.  When I try to use the Make Manifold feature, I get the following permissions error.
![Screen Shot 2019-10-24 at 4 24 15 PM](https://user-images.githubusercontent.com/4418497/67522732-44f79f80-f67b-11e9-9679-1e78741b7915.png)

Note, I installed Blender 2.8 in a local directory.  Below are the permissions shown for the various scripts.  I do not seem to have exe permissions on the .py scripts.
![Screen Shot 2019-10-24 at 4 29 33 PM](https://user-images.githubusercontent.com/4418497/67522848-7d977900-f67b-11e9-93e4-33e0bc48ea69.png)

Any thoughts?  Thanks.

**Comment by emanuelegissi** [comment]
Dear Randy,
the py files should not need the exe permission because they are executed
through Blender.

Try to add the exe permission to the following binary file:
blenderfds28x/bin/quadriflow/manifold_Darwin

I am experimenting the use of external processes, and I need to include
their binaries for Linux, Win, and MacOS.

Emanuele

**Comment by emanuelegissi** [comment]
Did it work?
Ema

**Comment by rmcdermo** [comment]
Well, I do not get the same error, but I a different one.  Probably the geom is too broken.

**Comment by emanuelegissi** [comment]
Can you share the geometry with me and I'll take a look?
Ema

**Comment by rmcdermo** [comment]
Here is the .stl file.
[channel.stl.txt](https://github.com/firetools/blenderfds28x/files/3793291/channel.stl.txt)

All I did was go to Edit mode and then Make Manifold.

**Comment by emanuelegissi** [comment]
The channel .stl file was indeed very broken.

First I tried with make manifold (resolution 1200). It worked here, and I
attach the result.
I think this rounded channel is not exactly what what you want.

So I remade it from scratch in 5 minutes, using the extrusion technique
that you find here:
https://www.blender3darchitect.com/blender-2-8-for-architecture/?source=sidebar

And I attach the new result. I suppose this is muuuch better for you.

My suggestion is: never never never use the stl format.
The stl format is broken by default. As explained here:
https://en.wikipedia.org/wiki/STL_(file_format)
it is simply a collection of triangles, and each triangle repeats the
definition of its vertices. So a little rounding error and the vertices do
not match any more.

The Wavefront OBJ format (https://en.wikipedia.org/wiki/Wavefront_.obj_file)
is very similar to what you devised for GEOMs: a list of vertices and a
list of triangles linked to the vertices. So it is much better at
preventing errors.

Anyway, what I understand from your experience is that the make manifold
tools is not yet ready for prime time. I'll work more on it.

Cheers,
Ema

**Comment by rmcdermo** [comment]
Ema,
Thanks for looking at this.  Yes, I know the wisdom you preach.  I was only sending you this Issue because, as a user, it is reasonable to expect that at button that says "make manifold" will do that.  So far, my experience is that this is not really possible for any practical situation.  And if it is only possible 1 % of the time, better not to advertise it.

**Comment by emanuelegissi** [comment]
Dear Randy,
indeed the "make manifold" button is the holy grail of computational
geometry. It works 1% of the time, and that only time the result is not
what you want... So, not ready for releasing. I will backtrack on that.
Emanuele
